### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
adapter_name_or_path: /storage/dataset/training_data/saves/Qwen2.5-VL-7B-Instruct/lora/foodVI-epoch3/checkpoint-13893
trust_remote_code: true

### method
finetuning_type: lora

# export
export_dir: /storage/dataset/training_data/merged/Qwen2.5-VL-7B-Instruct-Lora-SFT-Checkpoint-13893
export_device: auto
