### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
# lora_alpha: 16
# lora_target: q_proj,v_proj

### dataset
# dataset: uecfood256_sharegpt_train
dataset: foodsg233_sharegpt_train
template: qwen2_vl
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output/training/qwen2.5_vl-7b/lora/sft/foodsg233/Mar21
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
# bf16: true
ddp_timeout: 180000000
weight_decay: 0.01
label_smoothing_factor: 0.1  # avoid model overfitting by softening the target distribution of labels from one-hot vectors [1,0,0] to [0.9,0.05,0.05].

report_to: wandb

### eval
val_size: 0.15
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 50
